version: '2'
services: 
    xnat-web:
       build: <path to tomcat folder>
       ports:
        - "8081:8080"
       volumes:
         - <path to webapps folder>:/opt/tomcat/webapps
         - <path to plugins folder>:/data/xnat/home/plugins
         - /var/run/docker.sock:/var/run/docker.sock
       expose:
        - "8080"
       links:
        - xnat-db    
    xnat-db:
       build: <path to postgres folder>
       expose:
         - "5432"
       volumes:
         - <path to postgres-data folder which will be created on the file in the parent folder>:/var/lib/postgresql/data
    xnat-nginx:
       build: <path to nginx folder>
       ports:
        - "80:80"
       expose: 
        - "80"
       links:
         - xnat-web
